bump docker

diff --git a/src/github.com/docker/docker/contrib/init/sysvinit-redhat/docker b/src/github.com/docker/docker/contrib/init/sysvinit-redhat/docker
--- a/src/github.com/docker/docker/contrib/init/sysvinit-redhat/docker
+++ b/src/github.com/docker/docker/contrib/init/sysvinit-redhat/docker
@@ -41,7 +41,14 @@ prestart() {
 }
 
 start() {
-    [ -x $exec ] || exit 5
+    if [ ! -x $exec ]; then
+      if [ ! -e $exec ]; then
+        echo "Docker executable $exec not found"
+      else
+        echo "You do not have permission to execute the Docker executable $exec"
+      fi	      
+      exit 5
+    fi
 
     check_for_cleanup
 
@@ -58,7 +65,13 @@ start() {
         while [ ! -f $pidfile -a $tries -lt 10 ]; do
             sleep 1
             tries=$((tries + 1))
+            echo -n '.'
         done
+        if [ ! -f $pidfile ]; then
+          failure
+          echo
+          exit 1
+        fi
         success
         echo
     else
