create final releases based on given version
Signed-off-by: Glyn Normington <gnormington@pivotal.io>

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -3,6 +3,12 @@
 
 set -e -x
 
+VERSION=$(cat ./version/number)
+if [ -z "$VERSION" ]; then
+  echo "missing version number"
+  exit 1
+fi
+
 source ./garden-ci/bosh_environment
 
 bosh target ${BOSH_TARGET}
@@ -13,6 +19,6 @@ bosh -n upload stemcell bosh-stemcells/*.tgz --skip-if-exists
 
 cd release-develop/
 
-bosh -n create release
+bosh -n create release --final --version "${VERSION}"
 bosh -n upload release --skip-if-exists
 bosh -n deploy
